663
start time : 2019-10-26 08:38:37.072442
iotlog_ 2018-01 1973
iotlog_ 2018-01 2120
iotlog_ 2018-01 1115
iotlog_ 2018-01 4662
iotlog_ 2018-01 3485
iotlog_ 2018-01 3041
iotlog_ 2018-01 3851
iotlog_ 2018-01 4950
iotlog_ 2018-01 4534
iotlog_ 2018-01 1594
iotlog_ 2018-01 1574
iotlog_ 2018-01 4462
iotlog_ 2018-01 2111
iotlog_ 2018-01 2653
iotlog_ 2018-01 1583
iotlog_ 2018-01 3753
iotlog_ 2018-01 3817
iotlog_ 2018-01 4699
iotlog_ 2018-01 1083
iotlog_ 2018-01 3980
iotlog_ 2018-01 4859
iotlog_ 2018-01 1225
iotlog_ 2018-01 4891
iotlog_ 2018-01 4504
iotlog_ 2018-01 2871
iotlog_ 2018-01 2203
iotlog_ 2018-01 3228
iotlog_ 2018-01 4570
iotlog_ 2018-01 1115
iotlog_ 2018-01 2176
iotlog_ 2018-01 3954
iotlog_ 2018-02 1743
iotlog_ 2018-02 2546
iotlog_ 2018-02 4056
iotlog_ 2018-02 2666
iotlog_ 2018-02 3340
iotlog_ 2018-02 1854
iotlog_ 2018-02 4930
iotlog_ 2018-02 1272
iotlog_ 2018-02 4964
iotlog_ 2018-02 4366
iotlog_ 2018-02 3388
iotlog_ 2018-02 4185
iotlog_ 2018-02 2252
iotlog_ 2018-02 3208
iotlog_ 2018-02 1842
iotlog_ 2018-02 3968
iotlog_ 2018-02 2560
iotlog_ 2018-02 3291
iotlog_ 2018-02 4544
iotlog_ 2018-02 2489
iotlog_ 2018-02 3898
iotlog_ 2018-02 3583
iotlog_ 2018-02 4750
iotlog_ 2018-02 2265
iotlog_ 2018-02 2061
iotlog_ 2018-02 4004
Traceback (most recent call last):
  File "task_Elasticsearch_template.py", line 89, in <module>
    elsearch.index(index=index_name+index_suffix,body=template)
  File "/root/anaconda3/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/root/anaconda3/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 364, in index
    "POST", _make_path(index, doc_type, id), params=params, body=body
  File "/root/anaconda3/lib/python3.7/site-packages/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/root/anaconda3/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 252, in perform_request
    self._raise_error(response.status, raw_data)
  File "/root/anaconda3/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 181, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.AuthorizationException: AuthorizationException(403, 'cluster_block_exception', 'index [iotlog_2018-02] blocked by: [FORBIDDEN/12/index read-only / allow delete (api)];')
